<?php

/**
 * Verify the class-map generator has a non-mutating, fail-closed check mode.
 */

if ( PHP_SAPI !== 'cli' )
{
    fwrite( STDERR, "This script must be run from the command line.\n" );
    exit( 1 );
}

$plugin_root = dirname( __DIR__, 2 );
$generator   = $plugin_root . '/build/generate-class-map.php';
$fixture     = $plugin_root . '/.item14-class-map-test';
$wrapper     = $fixture . '/run.php';
$errors      = [];

try
{
    mkdir( $fixture . '/includes', 0775, true );
    file_put_contents(
        $fixture . '/includes/class-sentient-forms-sample.php',
        "<?php\n"
        . "\$references = [ Sentient_Forms_Unrelated::class => Sentient_Forms_Not_A_Declaration::value ];\n"
        . "\$anonymous = new #[Item14Marker] class extends Sentient_Forms_Attributed_Anonymous {};\n"
        . "class Sentient_Forms_Sample {}\n"
    );
    $stale = "<?php\nreturn [];\n";
    file_put_contents( $fixture . '/includes/class-map.php', $stale );
    file_put_contents(
        $wrapper,
        "<?php\ndefine('SENTIENT_FORMS_PLUGIN_DIR_FOR_BUILD', \$argv[1] . DIRECTORY_SEPARATOR);\n"
        . "\$generator = \$argv[2];\n\$argv = [\$generator, \$argv[3] ?? ''];\nrequire \$generator;\n"
    );

    $red = run_generator( $wrapper, $fixture, $generator, '--check' );
    if ( 0 === $red['status'] )
    {
        $errors[] = 'Check mode accepted a stale class map.';
    }
    if ( $stale !== file_get_contents( $fixture . '/includes/class-map.php' ) )
    {
        $errors[] = 'Check mode mutated the stale class map.';
    }

    $generated = run_generator( $wrapper, $fixture, $generator, '' );
    if ( 0 !== $generated['status'] )
    {
        $errors[] = 'Class-map generation failed.';
    }
    if ( ! defined( 'ABSPATH' ) )
    {
        define( 'ABSPATH', $fixture . DIRECTORY_SEPARATOR );
    }
    $generated_map = include $fixture . '/includes/class-map.php';
    if ( [ 'Sentient_Forms_Sample' ] !== array_keys( is_array( $generated_map ) ? $generated_map : [] ) )
    {
        $errors[] = 'Class constants or attributed anonymous classes were misclassified as declarations.';
    }
    $green = run_generator( $wrapper, $fixture, $generator, '--check' );
    if ( 0 !== $green['status'] )
    {
        $errors[] = 'Check mode rejected freshly generated bytes.';
    }
}
finally
{
    remove_owned_directory( $fixture );
}

if ( [] !== $errors )
{
    fwrite( STDERR, "Class-map generator test failed:\n" );
    foreach ( $errors as $error )
    {
        fwrite( STDERR, "- {$error}\n" );
    }
    exit( 1 );
}

echo "Class-map generator test passed: stale check refused, generation canonical, check non-mutating.\n";

/**
 * @return array{status:int,stdout:string,stderr:string}
 */
function run_generator( string $wrapper, string $fixture, string $generator, string $mode ): array
{
    $process = proc_open(
        [ PHP_BINARY, $wrapper, $fixture, $generator, $mode ],
        [
            1 => [ 'pipe', 'w' ],
            2 => [ 'pipe', 'w' ],
        ],
        $pipes
    );
    $stdout = (string) stream_get_contents( $pipes[1] );
    fclose( $pipes[1] );
    $stderr = (string) stream_get_contents( $pipes[2] );
    fclose( $pipes[2] );
    return [ 'status' => proc_close( $process ), 'stdout' => $stdout, 'stderr' => $stderr ];
}

function remove_owned_directory( string $path ): void
{
    if ( ! is_dir( $path ) || '.item14-class-map-test' !== basename( $path ) )
    {
        return;
    }
    $iterator = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator( $path, FilesystemIterator::SKIP_DOTS ),
        RecursiveIteratorIterator::CHILD_FIRST
    );
    foreach ( $iterator as $item )
    {
        $item->isDir() ? @rmdir( $item->getPathname() ) : @unlink( $item->getPathname() );
    }
    @rmdir( $path );
}
