<?php
// Sentient Forms Class Map - Auto-generated by build/generate-classmap.php
// Do not edit this file manually.

return [
	'Sentient_Forms_Abstract_Action' => __DIR__ . '/actions/abstract-sentient-forms-action.php',
	'Sentient_Forms_Abstract_Llm' => __DIR__ . '/llms/abstract-class-llm.php',
	'Sentient_Forms_Abstract_Llm_Google' => __DIR__ . '/llms/google/abstract-class-llm-google.php',
	'Sentient_Forms_Action_Interface' => __DIR__ . '/interfaces/interface-sentient-forms-action.php',
	'Sentient_Forms_Action_Registry' => __DIR__ . '/actions/class-sentient-forms-action-registry.php',
	'Sentient_Forms_Adapter_Interface' => __DIR__ . '/interfaces/interface-sentient-forms-adapter.php',
	'Sentient_Forms_Admin' => __DIR__ . '/admin/class-sentient-forms-admin.php',
	'Sentient_Forms_Async_Handler' => __DIR__ . '/class-sentient-forms-async-handler.php',
	'Sentient_Forms_Autoloader' => __DIR__ . '/class-sentient-forms-autoloader.php',
	'Sentient_Forms_Entry_Evaluation_Action' => __DIR__ . '/actions/class-sentient-forms-entry-evaluation-action.php',
	'Sentient_Forms_Form_Adapter_Registry' => __DIR__ . '/adapters/forms/class-forms-adapter-registry.php',
	'Sentient_Forms_Google_Gemini_2_0_Flash_Lite_Llm' => __DIR__ . '/llms/google/class-model-google-gemini-2_0-flash-lite.php',
	'Sentient_Forms_Google_Gemini_2_0_Flash_Llm' => __DIR__ . '/llms/google/class-model-google-gemini-2_0-flash.php',
	'Sentient_Forms_Google_Gemini_2_5_Flash_Preview_Llm' => __DIR__ . '/llms/google/class-model-google-gemini-2_5-flash-preview.php',
	'Sentient_Forms_Google_Gemini_2_5_Pro_Preview_Llm' => __DIR__ . '/llms/google/class-model-google-gemini-2_5-pro-preview.php',
	'Sentient_Forms_Gravity_Forms_Adapter' => __DIR__ . '/adapters/forms/class-sentient-forms-gravity-forms-adapter.php',
	'Sentient_Forms_Llm_Api_Client' => __DIR__ . '/api/class-sentient-forms-llm-api-client.php',
	'Sentient_Forms_Llm_Capability' => __DIR__ . '/enums/LLMs.php',
	'Sentient_Forms_Llm_Cost_Tier' => __DIR__ . '/enums/LLMs.php',
	'Sentient_Forms_Llm_Model_Interface' => __DIR__ . '/interfaces/interface-sentient-forms-llm-model.php',
	'Sentient_Forms_Llm_Model_Registry' => __DIR__ . '/llms/sentient-forms-llm-registry.php',
	'Sentient_Forms_Llm_Provider' => __DIR__ . '/enums/LLMs.php',
	'Sentient_Forms_Llm_Status' => __DIR__ . '/enums/LLMs.php',
	'Sentient_Forms_Plugin' => __DIR__ . '/class-sentient-forms-plugin.php',
	'Sentient_Forms_Spam_Analysis_Action' => __DIR__ . '/actions/class-sentient-forms-spam-analysis-action.php',
];
